### ISSUE TITLE
Unhandled JS Exception. Global Code.

### ISSUE THREAD

**Issue by realvadim** [callstack/react-native-opentok#15]
@grabbou I have difficulties integrating the library with my project. What I do is below:

1) I have project, which works fine.
2) I need to use react-native-opentok library.
3) In the guide I only need to add one line to my podfile and run 'pod install'. But in that pod line there is :path = '../node_modules/react-native-opentok'. I do not have it currently.
4) I run 'npm install react-native-opentok' and as a result the folder is created and only contains one file: package.json.
5) I go back to my ios directory and run pod install.
6) I get error .podspec file is missing.
7) Having downloaded it from git I place this file next to package.json in 'node_modules/react-native-opentok'
8) Run pod install again. Now it gets to succefully installing the pod.
9) Run 'react-native run-ios'
10) Boom! Crash! Unhandled JS Exception. Global Code.
[errorv1.txt](https://github.com/callstack-io/react-native-opentok/files/793215/errorv1.txt)

What am I doing wrong? Please help, wasted several days on this already, nothing helps. I have attached console output from Xcode.

Thanks in advance!

**Comment by ainurb** [comment]
@grabbou @mike866 @radko93

**Comment by priya-vr** [comment]
I am getting same error "Unhandled JS Exception" during running iOS

**Comment by mike866** [comment]
Hey!

Thanks for your feedback. We rewrote the library completely, which results in API changes and many bug fixes. If the issue still persists on the latest version, please re-open it. 

Thanks!
