### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ainurb** [callstack/react-native-opentok#16]
Please, update installation guide for ios. 
pod 'react-native-opentok', :path => '../node_modules/react-native-opentok' doesn't work.

**Comment by patrickpoh** [comment]
did u manage to install it? thanks!

**Comment by ainurb** [comment]
@patrickpoh I could install it by changing react-native-opentok.podspec file to this: 
`require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "react-native-opentok"
  s.version      = package["version"]
  s.summary      = "An OpenTok SDK for react-native"
  s.authors      = {
    'Mike Grabowski' => 'mike@callstack.io',
    'Mike Chudziak' => 'mike.chudziak@callstack.io',
  }

  s.homepage     = "https://github.com/callstack/react-native-video"

  s.license      = "MIT"
  s.platform     = :ios, "7.0"

  s.source       = { :git => "https://github.com/bradrlaw/react-native-opentok.git", :tag => "#{s.version}" }

  s.source_files  = "*.{h,m}"

  s.dependency "OpenTok"
end
`

**Comment by mike866** [comment]
Hey!

Thanks for your feedback. We rewrote the library completely, which results in API changes and many bug fixes. If the issue still persists on the latest version, please re-open it. 

Thanks!
