### ISSUE TITLE
SessionManager.connect undefined is not an object

### ISSUE THREAD

**Issue by konstantin-mohin** [callstack/react-native-opentok#17]
Hey, 

I included the package to a project , it compiled well, but when I run it on android device, I'm getting the error.

"dependencies": {
    "firebase": "^3.3.2",
    "native-base": "^0.5.22",
    "react": "^15.4.1",
    "react-native": "^0.39.0",
    "react-native-datepicker": "^1.4.3",
    "react-native-firestack": "^2.3.5",
    "react-native-fs": "^2.0.1-rc.2",
    "react-native-gifted-chat": "0.0.10",
    "react-native-incall-manager": "^1.5.4",
    "react-native-modal-datetime-picker": "^4.0.0",
    "react-native-oauth": "^2.1.2",
    "react-native-opentok": "github:callstack-io/react-native-opentok",
    "react-native-router-flux": "^3.37.0",
    "react-native-scrollable-tab-view": "^0.6.0",
    "react-native-vector-icons": "^2.1.0",
    "react-redux": "^4.4.5",
    "redux": "^3.6.0",
    "redux-module-builder": "^0.3.2",
    "redux-persist": "^3.5.0",
    "redux-thunk": "^2.1.0"
  },

**Comment by mike866** [comment]
Hey!

Thanks for your feedback. We rewrote the library completely, which results in API changes and many bug fixes. If the issue still persists on the latest version, please re-open it. 

Thanks!
