### ISSUE TITLE
How to change camera position?

### ISSUE THREAD

**Issue by hirokimoto** [callstack/react-native-opentok#18]
I'd like to change camera position in javascript code, but I think this package does not support this function yet.
Can you implement this function in both of iOS and Android?

**Comment by raiden-abe** [comment]
This library does not support the function to change camera position yet. I think you should customize this library yourself.

**Comment by mike866** [comment]
Hey!

Thanks for your feedback. We rewrote the library completely, which results in API changes and many bug fixes. If the issue still persists on the latest version, please re-open it. 

Thanks!
