### ISSUE TITLE
Unable to install via pod install

### ISSUE THREAD

**Issue by patrickpoh** [callstack/react-native-opentok#19]
Hi, when i try to install via pod install.

this error appears, [!] No podspec found for `react-native-opentok` in `../node_modules/react-native-opentok`

**Comment by MieszkoGulinski** [comment]
Try workaround at #25

**Comment by mike866** [comment]
Hey!

Thanks for your feedback. We rewrote the library completely, which results in API changes and many bug fixes. If the issue still persists on the latest version, please re-open it. 

Thanks!
