### ISSUE TITLE
Problem with 2 Subscriber and 2 Publisher

### ISSUE THREAD

**Issue by LucasSouzaa** [callstack/react-native-opentok#22]
Hello, I'm having trouble creating a video chat.

- First if I put a publisher and a subscriber at the same time, the subscriber starts to reproduce the publisher of the own user.

- I tried to assemble the components alternately listening when each user enters the room, but sometimes the last subscriber to be created gets the black screen or hangs.

Thanks in advance

**Comment by hirokimoto** [comment]
This library has definitely that kind of issues. You should customize this library to fix those issues.

**Comment by morksinaanab** [comment]
The main issue is that each component, the publisherview, the subscriberview and the sessionmanager each have their own instance of a session. Which means if you create a subscriber and a publisher at the same time, each will have it's own session, effectively listening to each other. I working now to make the session object a singleton shared by each three components. I'm getting it fixed, but not really nice yet. Will share a PR in the next two weeks hopefully.

**Comment by mike866** [comment]
Hey!

Thanks for your feedback. We rewrote the library completely, which results in API changes and many bug fixes. If the issue still persists on the latest version, please re-open it. 

Thanks!
