### ISSUE TITLE
Rewrite library

### ISSUE THREAD

**Issue by mike866** [callstack/react-native-opentok#36]
Things to be implemented before first release:

- [x] Reimplement library using session singletons & new API (iOS)
- [x] Reimplement library using session singletons & new API (Android)
- [x] Attach correct event handlers for current components
- [x] Investigate if multiple js `init`s works
- [x] Update README
- [x] Fix reload issue (iOS)

For future releases:

- [ ] Migrate from depreacted ios methods
- [ ] Cover more SDK
- [ ] Add native tests?

**Comment by mike866** [comment]
Also investigate if is worth storing API keys in `Info.plist` and `AndroidManifest.xml`.

**Comment by rezonjov** [comment]
Hi @mike866, just wanted to let you know, we just tested your newly pushed branch 'rewrite' but it seems subscriberView is still a blank screen on Android. Glad to see the repo is updated frequently.

**Comment by mike866** [comment]
Hey @rezonjov! Can you test it with latest implementation? We've managed to fix the issue on our end, but if it still occurs It would be great if you can post bug report here :)

**Comment by mike866** [comment]
Branch is still under heavy development, just FYI

**Comment by rezonjov** [comment]
@mike866, my apologies, turns out the blank screen is due to the css issue on our end. The subscriberView works. :)
