### ISSUE TITLE
[Not a bug] Syncing up sessionID and Token to another app

### ISSUE THREAD

**Issue by masudhossain** [callstack/react-native-opentok#37]
I copied this [repo](https://github.com/aullman/opentok-meet) and they create a sessionId and Token whenever someone goes to a room such as example.com/123. 

I'm curious how one would hook up this react-native-opentok to the same sessionId and token as the other app at example.com/123.

**Comment by mike866** [comment]
Hey!

Thanks for your feedback. We rewrote the library completely, which results in API changes and many bug fixes. If the issue still persists on the latest version, please re-open it. 

Thanks!
