### ISSUE TITLE
The code is not compatible with react 15.5+

### ISSUE THREAD

**Issue by clementdevosmc** [callstack/react-native-opentok#41]
Hello, 

I've been trying (after ejecting expo and setup my project...) to implement this in my project but the code is using React.PropTypes that have been moved to the 'prop-types' package. 

I think it won't be a big update to use these prop types instead of React's. 
I'll make a PR tomorrow because this is blocking if you want the code to run on React 15.5+

Do you see anything else blocking this library with react 15.5+?

Source https://reactjs.org/docs/typechecking-with-proptypes.html 

Cheers, 
Clément

**Comment by clementdevosmc** [comment]
Created PR #43

**Comment by mike866** [comment]
Hey!

Thanks for your feedback. We rewrote the library completely, which results in API changes and many bug fixes. If the issue still persists on the latest version, please re-open it. 

Thanks!
