### ISSUE TITLE
Disconnect cleanup

### ISSUE THREAD

**Issue by krokhale** [callstack/react-native-opentok#48]
When i invoke OpenTok.disconnectAll()  OR OpenTok.disconnect(sessionId)

It seems the cleanup isn't taking place and the screen hangs, it never disconnects at all.

**Comment by krokhale** [comment]
Not a mobile developer, but i did some digging. Have commented out the lines at which it is failing:

<img width="871" alt="screen shot 2017-10-16 at 2 55 43 pm" src="https://user-images.githubusercontent.com/173148/31606727-88ad308a-b287-11e7-9689-0e6bcc4db914.png">

**Comment by dratwas** [comment]
@krokhale Thanks for your report. I'm working on fixing it.

**Comment by krokhale** [comment]
Thanks @dratwas Let me know if I can help you out with anything!

It seems like this issue is similar to the issue you described on your blog related to singleton sessions.

For instance if during development I were to refresh using CMD+R the video hangs. I think the refresh and the session disconnect issues are related.

Also, something I noticed, though the video hangs on the mobile device, the person on the other end does not see anything. So the session does terminate. It's just the cleanup after session disconnect on the mobile device that causes the issue.

**Comment by krokhale** [comment]
Hey @dratwas was wondering if any word on this? Thanks!

**Comment by philolo1** [comment]
@krokhale you could always only use one session and delete it, i think then you dont have this issue, why do you need multiple sessions anyway?

**Comment by krokhale** [comment]
@philolo1 that's a great idea and i guess i could work with one session. But how do i stop publishing? I don't see anything in the docs that could stop publishing.

How do you delete a session?

**Comment by philolo1** [comment]
@krokhale if you stop OpenTok.disconnect(sessionId) you stop publish as you disconnected from the session.

**Comment by krokhale** [comment]
Right, i did try that and the app hangs up. I could try it again and see if i was missing something. Also i am using an iPhone, haven't tested on an Android yet.

Let me make a gist and share it with you in a little bit.

**Comment by philolo1** [comment]
@krokhale good to know, havent tried ios yet. i use https://github.com/500LABS/HotBox for ios, which is more mature i believe.

**Comment by krokhale** [comment]
Ah, yes i did come across that, but i guess i chose this because this supported both Android and iPhone. Come to think of it, it might not be a bad idea to use HotBox for ios and this for Android.

**Comment by philolo1** [comment]
yeah @krokhale the bad thing about this library is that its not supporting multiple subscribers.

**Comment by RoyalDeveloper2015** [comment]
I have the same issue with OpenTok.disconnect(sessionId);

This is not working actually. please help me on that.

**Comment by dratwas** [comment]
Hey guys. I already fixed this issue. Sorry for the delay. Thanks for your report.

@philolo1 What you mean about multiple subscribers?
This library supports multiple session so you can connect with two sessions and then render two subscribers view with different `sessionId` prop.

**Comment by RoyalDeveloper2015** [comment]
hi @dratwas , that is not working yet.

**Comment by dratwas** [comment]
@RoyalDeveloper2015 PR is still Open.
https://github.com/callstack/react-native-opentok/pull/52

**Comment by RoyalDeveloper2015** [comment]
That is working now, Thank you.
