### ISSUE TITLE
Video freeze after start between iOS and android

### ISSUE THREAD

**Issue by renanpupin** [callstack/react-native-opentok#75]
When I try to connect a android and iOS device everything works perfect.
But after 2 seconds the video freeze on android and never back, the audio continue to work perfectly.

The test was made under good connectivity and tested with 3 android phones and 2 iphones.

**Comment by renanpupin** [comment]
Problem solved updating the android SDK to 2.12+ (#67).

**Comment by krokhale** [comment]
@renanpupin 2.12+ works great, have you been able to disconnect the calls smoothly? It's been crashing for me on Android.
