### ISSUE TITLE
Showing both SubscriberView and PublisherView together is crashing the app.

### ISSUE THREAD

**Issue by ivks** [callstack/react-native-opentok#8]
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105d8234b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000109af321e objc_exception_throw + 48
	2   CoreFoundation                      0x0000000105c98d8f -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 351
	3   CoreFoundation                      0x0000000105c98bfb +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	4  XXXX                              0x0000000103d2b27f -[RCTOpenTokPublisherView session:connectionCreated:] + 479
	5   XXXX                              0x0000000103d3e507 __47-[OTKitSessionDelegate otkitConnectionCreated:]_block_invoke + 135
	6   libdispatch.dylib                   0x000000010b6d2980 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x000000010b6fc0cd _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000010b6dc8d6 _dispatch_main_queue_callback_4CF + 406
	9   CoreFoundation                      0x0000000105d464f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	10  CoreFoundation                      0x0000000105d0bf8d __CFRunLoopRun + 2205
	11  CoreFoundation                      0x0000000105d0b494 CFRunLoopRunSpecific + 420
	12  GraphicsServices                    0x000000010c49aa6f GSEventRunModal + 161
	13  UIKit                               0x0000000107ce7964 UIApplicationMain + 159
	14  XXX                              0x0000000103c469df main + 111
	15  libdyld.dylib                       0x000000010b74868d start + 1
	16  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by dskoneczny** [comment]
@ivks 
Did you solve the problem?

**Comment by mike866** [comment]
Hey!

Thanks for your feedback. We rewrote the library completely, which results in API changes and many bug fixes. If the issue still persists on the latest version, please re-open it. 

Thanks!
