### ISSUE TITLE
Last version isn't available

### ISSUE THREAD

**Issue by Carlosp16** [callstack/react-native-opentok#99]
I saw you release a last version recently but isn't available on npm or yarn. The last version available is the 2.0.1.

**Comment by MaFranceschi** [comment]
Yeah! I noticed that, it could be very useful if I can use the new events related to reconnect ON_SESSION_DID_RECONNECTING and ON_SESSION_DID_BEGIN_RECONNECTING.

**Comment by MaFranceschi** [comment]
I saw they release a new version on npm (2.1.0) and already included all the new events. Please close this @Carlosp16
